# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 504875724c0271fd47ad551690f4c83601554a94d90a291bb85e4ea1483a8ae857f9fb931db2d1e25f1540861780deacd616e880574d7c3d3246e972a71f2725

test:
  secret_key_base: 1d6a936e81b905e579fe754f48bec4e5b1cad7d1a8282489517863fd2912c40acbd3bcf2d9a9feaecdb6510e034acdc1e3cb39803a1231b4bc5553c9bd5aa0b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
